/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */



/**
 *
 * @author otaku
 */
public class AudioSend extends javax.swing.JFrame {
    private SenData snDObject= null;
    private static SendData snDaObject= null;
    private int port= 0;
    private static AudioSend adoSndObject= null;

    /**
     * Creates new form AudioSend
     */
    public AudioSend(SenData snDObject, int port) {
        this.snDObject= snDObject;
        adoSndObject= this;
        this.port= port;
        snDaObject= new SendData(port, "SENDER");
        snDaObject.connect();
        initComponents();
        snDaObject.initialize();
        main(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabel1 = new javax.swing.JLabel();
    StartButton = new javax.swing.JButton();
    DisconnectButton = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle("Durara Audio Sender");
    setAlwaysOnTop(true);
    setBackground(java.awt.Color.lightGray);
    setBounds(new java.awt.Rectangle(300, 300, 100, 100));
    setLocation(new java.awt.Point(600, 600));
    setMinimumSize(new java.awt.Dimension(220, 100));
    setPreferredSize(new java.awt.Dimension(220, 100));
    setSize(new java.awt.Dimension(220, 100));
    getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    jLabel1.setText("Connected");
    getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 78, -1));

    StartButton.setText("Start");
    StartButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        StartButtonActionPerformed(evt);
      }
    });
    getContentPane().add(StartButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

    DisconnectButton.setText("Disconnect");
    DisconnectButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        DisconnectButtonActionPerformed(evt);
      }
    });
    getContentPane().add(DisconnectButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, -1, -1));

    pack();
  }// </editor-fold>//GEN-END:initComponents

    private void StartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartButtonActionPerformed
        snDaObject.start();
           snDaObject.read();
            
            Thread sndThrdObject= new Thread(snDaObject);
            sndThrdObject.start();// TODO add your handling code here:
    }//GEN-LAST:event_StartButtonActionPerformed

    private void DisconnectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisconnectButtonActionPerformed
        snDObject.write("St0pAudI0ChAt");
        snDObject.run();
        adoSndObject.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_DisconnectButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AudioSend.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AudioSend.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AudioSend.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AudioSend.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            adoSndObject.setVisible(true);
                
            
            }
        });
    }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton DisconnectButton;
  private javax.swing.JButton StartButton;
  private javax.swing.JLabel jLabel1;
  // End of variables declaration//GEN-END:variables
}
