/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */





/**
 *
 * @author otaku
 */
public class AudioReciever extends javax.swing.JFrame {
    private Client clntObject= null;
    private static ReadData rDObject= null;
    private Server svrObject= null;
    private String ipAddress= null;
    private static AudioReciever adoRcvrObject= null;
    private SenData snDObject= null;
    /**
     * Creates new form AudioReciever
     */
    public AudioReciever(Client clntObject, ReadData rDObject, String ipAddress, SenData snDObject) {
        this.clntObject= clntObject;
        adoRcvrObject= this;
        this.rDObject= rDObject;
        this.ipAddress= ipAddress;
        this.snDObject= snDObject;
        initComponents();
        
        main(null);
    }
    
    public AudioReciever(Server svrObject, ReadData rDObject, String ipAddress, SenData snDObject) {
        this.svrObject= svrObject;
        adoRcvrObject= this;
        this.rDObject= rDObject;
        this.ipAddress= ipAddress;
        this.snDObject= snDObject;
        initComponents();
        
        main(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabel1 = new javax.swing.JLabel();
    StartButton = new javax.swing.JButton();
    StopButton = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle("Durarara Audio Reciever");
    setAlwaysOnTop(true);
    setBackground(java.awt.Color.lightGray);
    setBounds(new java.awt.Rectangle(300, 300, 100, 100));
    setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    setLocation(new java.awt.Point(300, 300));
    setMinimumSize(new java.awt.Dimension(220, 100));
    setPreferredSize(new java.awt.Dimension(100, 50));
    setResizable(false);
    getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    jLabel1.setText("Reciever");
    jLabel1.setPreferredSize(new java.awt.Dimension(100, 250));
    getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 62, 20));

    StartButton.setText("Start");
    StartButton.setMaximumSize(new java.awt.Dimension(100, 250));
    StartButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        StartButtonActionPerformed(evt);
      }
    });
    getContentPane().add(StartButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

    StopButton.setText("Stop");
    StopButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        StopButtonActionPerformed(evt);
      }
    });
    getContentPane().add(StopButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, -1, -1));

    pack();
  }// </editor-fold>//GEN-END:initComponents

    private void StopButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StopButtonActionPerformed
      snDObject.write("St0pAudI0ChAt");
      snDObject.run();
      
      if(svrObject!= null) {
        
        svrObject.stopAudio();
      }
      else{
        clntObject.stopAudio();
      }
        
// TODO add your handling code here:
    }//GEN-LAST:event_StopButtonActionPerformed

  private void StartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartButtonActionPerformed
    rDObject.write();
    rDObject.start();
    Thread rdThrdObject= new Thread(rDObject);
    rdThrdObject.start();
    
    
// TODO add your handling code here:
  }//GEN-LAST:event_StartButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AudioReciever.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AudioReciever.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AudioReciever.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AudioReciever.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                adoRcvrObject.setVisible(true);
                
            }
        });
    }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton StartButton;
  private javax.swing.JButton StopButton;
  private javax.swing.JLabel jLabel1;
  // End of variables declaration//GEN-END:variables
}
