/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */





/**
 *
 * @author otaku
 */
public class DurararaServer extends javax.swing.JFrame {
    private String loginId= null;
    private int password= 5555;
    private static DurararaServer draSvrObject= null;
    private String ipAddress= null;

    /**
     * Creates new form DurararaServer
     */
    public DurararaServer() {
        draSvrObject= this;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabel2 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    jLabel4 = new javax.swing.JLabel();
    jLabel5 = new javax.swing.JLabel();
    LoginIdTextField = new javax.swing.JTextField();
    PasswordTextField = new javax.swing.JTextField();
    startServerButton = new javax.swing.JButton();
    incorrectLoginIdLabel = new javax.swing.JLabel();
    incorrectPaswordLabel = new javax.swing.JLabel();
    IncorrectLoginIdLabel1 = new javax.swing.JLabel();
    jLabel7 = new javax.swing.JLabel();
    jLabel6 = new javax.swing.JLabel();
    IPTextField = new javax.swing.JTextField();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle("Duarrara Server Login");
    setAlwaysOnTop(true);
    setBackground(java.awt.Color.lightGray);
    setBounds(new java.awt.Rectangle(600, 600, 400, 300));
    setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    setLocation(new java.awt.Point(300, 300));
    setPreferredSize(new java.awt.Dimension(400, 300));
    setResizable(false);
    setSize(new java.awt.Dimension(400, 300));
    getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel2.setText("Welcome to Durarara!!!");
    getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, -1, -1));

    jLabel3.setText("Please Enter your login id and password to start the server");
    getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

    jLabel4.setText("Login id:");
    getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, -1, -1));

    jLabel5.setText("Password:");
    getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, -1, -1));

    LoginIdTextField.setText("Dollars");
    LoginIdTextField.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        LoginIdTextFieldActionPerformed(evt);
      }
    });
    getContentPane().add(LoginIdTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 105, -1));

    PasswordTextField.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        PasswordTextFieldActionPerformed(evt);
      }
    });
    getContentPane().add(PasswordTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 105, -1));

    startServerButton.setText("Start Server");
    startServerButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        startServerButtonActionPerformed(evt);
      }
    });
    getContentPane().add(startServerButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 110, 40));
    getContentPane().add(incorrectLoginIdLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 234, -1, -1));
    getContentPane().add(incorrectPaswordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 277, -1, -1));

    IncorrectLoginIdLabel1.setText("  ");
    getContentPane().add(IncorrectLoginIdLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 350, -1));

    jLabel7.setText(" ");
    getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 277, 74, -1));

    jLabel6.setText("Ip Address:");
    getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, -1, -1));

    IPTextField.setText("localhost");
    IPTextField.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        IPTextFieldActionPerformed(evt);
      }
    });
    getContentPane().add(IPTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 104, -1));

    pack();
  }// </editor-fold>//GEN-END:initComponents

    private void LoginIdTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginIdTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LoginIdTextFieldActionPerformed

    private void startServerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startServerButtonActionPerformed
        
        loginId= LoginIdTextField.getText();
        password= Integer.parseInt(PasswordTextField.getText());
        ipAddress= IPTextField.getText();
        
        if(loginId.equals("Dollars")) {
            if(password==5555) {
               StartingServer strtSvrObject=  new StartingServer(password, draSvrObject,ipAddress);
            }
            else {
                IncorrectLoginIdLabel1.setText("Wrong Password...Please Try again!");
            }
        }
        else{
                IncorrectLoginIdLabel1.setText("Wrong Login id...Please Try again!");
        }
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_startServerButtonActionPerformed

    private void PasswordTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordTextFieldActionPerformed

    private void IPTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IPTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IPTextFieldActionPerformed

    public void set() {
        main(null);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DurararaServer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DurararaServer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DurararaServer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DurararaServer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DurararaServer().setVisible(true);
            }
        });
    }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JTextField IPTextField;
  private javax.swing.JLabel IncorrectLoginIdLabel1;
  private javax.swing.JTextField LoginIdTextField;
  private javax.swing.JTextField PasswordTextField;
  private javax.swing.JLabel incorrectLoginIdLabel;
  private javax.swing.JLabel incorrectPaswordLabel;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JLabel jLabel7;
  private javax.swing.JButton startServerButton;
  // End of variables declaration//GEN-END:variables
}
