/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */




/**
 *
 * @author otaku
 */
public class Recieve extends javax.swing.JFrame {
    private int port= 0;
    private SenData rdSndObject= null;
    private String ipAddress= null;
    private static Recieve rcvObject= null;
    private static recieveFile rcvFlObject= null;
    private String filename= null;
    
    /**
     * Creates new form Recieve
     */
    public Recieve(SenData rdSndObject, recieveFile rcvFlObject, String str) {
        rcvObject= this;
        filename= str;
        this.rdSndObject= rdSndObject;
        this.rcvFlObject= rcvFlObject;
        this.ipAddress= rdSndObject.getIp();
        port= rdSndObject.getPort();
        initComponents();
        main(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabel1 = new javax.swing.JLabel();
    AcceptButton = new javax.swing.JButton();
    DeclineButton = new javax.swing.JButton();
    jLabel2 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    FileNameLabel = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle("Durarara FTP");
    getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
    getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 102, 248, 16));

    AcceptButton.setText("Accept");
    AcceptButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        AcceptButtonActionPerformed(evt);
      }
    });
    getContentPane().add(AcceptButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 62, -1, -1));

    DeclineButton.setText("Decline");
    DeclineButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        DeclineButtonActionPerformed(evt);
      }
    });
    getContentPane().add(DeclineButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 62, -1, -1));

    jLabel2.setText("Do you Wish to recieve file from the other person");
    getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 12, -1, -1));

    jLabel3.setText("file: ");
    getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 34, -1, 22));
    getContentPane().add(FileNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 37, 258, 19));

    pack();
  }// </editor-fold>//GEN-END:initComponents

    private void AcceptButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AcceptButtonActionPerformed
        rcvFlObject.set();
        Thread rcvFlThdObject= new Thread(rcvFlObject);
        rcvFlThdObject.start();
        while(rcvFlThdObject.isAlive()){
            
        }
        rcvObject.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_AcceptButtonActionPerformed

    private void DeclineButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeclineButtonActionPerformed
        rcvObject.setVisible(false);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_DeclineButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Recieve.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Recieve.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Recieve.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Recieve.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                rcvObject.setVisible(true);
                
            }
        });
    }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton AcceptButton;
  private javax.swing.JButton DeclineButton;
  private javax.swing.JLabel FileNameLabel;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  // End of variables declaration//GEN-END:variables
}
