/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */



import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author otaku
 */
public class Server extends javax.swing.JFrame {
    private String sendMsh= null;
    private static ReaData rDObject= null;
    private static Server svrObject= null;
    private static StartingServer strtSvrObject= null;
    private static SenData rdSndObject= null;
    private static Thread rdSndThdObject= null;
    private Send sndObject= null;
    private static Recieve rcvObject= null;
    private static SendFile sndFileObject= null;
    private static recieveFile rcvFlObject= null;
    private static int port= 0;
    private static String ipAddress= null;
    private AudioReciever adoRcvrObject= null;
    private AudioSend adoSndObject= null;
    private ReadData rDaObject= null;
    private String setFileName= null;
    /**
     * Creates new form Server
     */
    public Server(ReaData rDObject, StartingServer strtSvrObject, SenData rdSndObject, Thread rdSndThdObject) {
        this.strtSvrObject= strtSvrObject;
        strtSvrObject.setVisible(false);
        svrObject= this;
        this.rdSndObject= rdSndObject;
        this.rdSndThdObject= rdSndThdObject;
        this.rDObject= rDObject;
        initComponents();
        this.main(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    sendButton = new javax.swing.JButton();
    chatTextField = new javax.swing.JTextField();
    jLabel1 = new javax.swing.JLabel();
    SendFileButton = new javax.swing.JButton();
    StartAudioButton = new javax.swing.JButton();
    DisconnectButton = new javax.swing.JButton();
    chatTextArea = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle("Durarara Server");
    setAlwaysOnTop(true);
    setBounds(new java.awt.Rectangle(600, 600, 500, 350));
    setLocation(new java.awt.Point(600, 600));
    setLocationByPlatform(true);
    setMinimumSize(new java.awt.Dimension(500, 350));
    setPreferredSize(new java.awt.Dimension(380, 320));
    setSize(new java.awt.Dimension(500, 350));
    getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    sendButton.setText("Send");
    sendButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        sendButtonActionPerformed(evt);
      }
    });
    getContentPane().add(sendButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 230, 67, -1));
    getContentPane().add(chatTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 232, 320, -1));

    jLabel1.setText("Server");
    getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, -1, -1));

    SendFileButton.setText("Send File");
    SendFileButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        SendFileButtonActionPerformed(evt);
      }
    });
    getContentPane().add(SendFileButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, -1, -1));

    StartAudioButton.setText("Start Audio chat");
    StartAudioButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        StartAudioButtonActionPerformed(evt);
      }
    });
    getContentPane().add(StartAudioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

    DisconnectButton.setText("Disconnect");
    DisconnectButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        DisconnectButtonActionPerformed(evt);
      }
    });
    getContentPane().add(DisconnectButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, -1, -1));

    chatTextArea.setBackground(java.awt.Color.white);
    chatTextArea.setForeground(java.awt.Color.green);
    chatTextArea.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    chatTextArea.setVerticalAlignment(javax.swing.SwingConstants.TOP);
    chatTextArea.setAutoscrolls(true);
    chatTextArea.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
    chatTextArea.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
    chatTextArea.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
    getContentPane().add(chatTextArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 400, 150));

    pack();
  }// </editor-fold>//GEN-END:initComponents

    public void set(String msg) {
        chatTextArea.setText(convertToMultiline(chatTextArea.getText()+"\n"+msg));
        
    }
    public String convertToMultiline(String orig)
    {
        return "<html>" + orig.replaceAll("\n", "<br>");
    }
    private void sendButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendButtonActionPerformed
        
        rdSndObject.write(chatTextField.getText());
        rdSndObject.run();
        chatTextArea.setText(convertToMultiline(chatTextArea.getText()+"\nYOU: "+chatTextField.getText()));
        chatTextField.setText("");
    }//GEN-LAST:event_sendButtonActionPerformed

    protected void startAudio() {
        rDaObject= new ReadData(port, "RECIEVER");
        rDaObject.connect();
        rDaObject.initialize();
        adoRcvrObject= new AudioReciever( svrObject, rDaObject, ipAddress, rdSndObject );
    }
    
    protected void stopAudio() {
        rDaObject.close();
        adoRcvrObject.setVisible(false);
    }
    
    private void SendFileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SendFileButtonActionPerformed
        rdSndObject.write("StaRtFil3");
        rdSndObject.run();
        sndFileObject= new SendFile(port, "SENDER" , ipAddress, rdSndObject);
        sndObject= new Send(sndFileObject);
                        
        // TODO add your handling code here:
    }//GEN-LAST:event_SendFileButtonActionPerformed

    private void StartAudioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartAudioButtonActionPerformed

        rdSndObject.write("StaRtAudI0ChaT");
        rdSndObject.run();
        adoSndObject= new AudioSend(rdSndObject, port);
        // TODO add your handling code here:
    }//GEN-LAST:event_StartAudioButtonActionPerformed

    private void DisconnectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisconnectButtonActionPerformed
        new DurararaServer().main(null);
        this.setVisible(false);
        rdSndObject.close();
        // TODO add your handling code here:
    }//GEN-LAST:event_DisconnectButtonActionPerformed

    protected void setfilename(String name){
      setFileName= name;
    }
    protected void startFile() {
        rcvFlObject= new recieveFile(port,"RECIEVER");
        rcvFlObject.connect();
        while(setFileName==null){}
        rcvFlObject.initialize();
        rcvObject= new Recieve(rdSndObject,rcvFlObject, setFileName );
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Server.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Server.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Server.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Server.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                rDObject.setServer(svrObject);
                svrObject.setVisible(true);
                port= rDObject.getport();
                ipAddress= rDObject.getIp();
                Thread rdThrdObject= new Thread(rDObject);
                rdThrdObject.start();
                
            /*    recieveFile rcvFlObject= new recieveFile(rdSndObject.getPort(),"RECIEVER");
                rcvFlObject.connect();
                String str= rcvFlObject.initializeTxt();
                rcvObject= new Recieve(rdSndObject,rcvFlObject, str );
            */
            }
        });
    }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton DisconnectButton;
  private javax.swing.JButton SendFileButton;
  private javax.swing.JButton StartAudioButton;
  private javax.swing.JLabel chatTextArea;
  private javax.swing.JTextField chatTextField;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JButton sendButton;
  // End of variables declaration//GEN-END:variables
}
